***EN
package com.bank.entity;

public class Customer {
    private int customerId;   // generated by DB
    private int accountId;    // generated by DB
    private String name;
    private String email;
    private String phone;

    // Constructor
    public Customer(String name, String email, String phone) {
        this.name = name;
        this.email = email;
        this.phone = phone;
    }

    // Getters & Setters
    public int getCustomerId() { return customerId; }
    public void setCustomerId(int customerId) { this.customerId = customerId; }

    public int getAccountId() { return accountId; }
    public void setAccountId(int accountId) { this.accountId = accountId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    @Override
    public String toString() {
        return "Customer [customerId=" + customerId + 
               ", accountId=" + accountId + 
               ", name=" + name + 
               ", email=" + email + 
               ", phone=" + phone + "]";
    }
}

**E
package com.bank.exception;

public class CustomerNotFoundException extends Exception {
    public CustomerNotFoundException(String message) {
        super(message);
    }
}

package com.bank.exception;

public class DataAccessException extends Exception {
    public DataAccessException(String message, Throwable cause) {
        super(message, cause);
    }
}

package com.bank.exception;

public class InvalidInputException extends Exception {
    public InvalidInputException(String message) {
        super(message);
    }
}

**con
package com.bank.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class ConnectionUtil {
    private static Connection con = null;

    private ConnectionUtil() {}

    public static Connection getConnection() throws SQLException {
        if (con == null || con.isClosed()) {
            con = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/customer_db", 
                "postgres", "your_password_here"
            );
        }
        return con;
    }
}

**
package com.bank.repository;

import com.bank.entity.Customer;
import com.bank.exception.CustomerNotFoundException;
import com.bank.exception.DataAccessException;
import com.bank.util.ConnectionUtil;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class CustomerRepository {

    public Customer insertCustomer(Customer customer) throws DataAccessException {
        String sql = "INSERT INTO customers (name, email, phone) VALUES (?, ?, ?) RETURNING customer_id, account_id";
        Connection con = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            con = ConnectionUtil.getConnection();
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, customer.getName());
            pstmt.setString(2, customer.getEmail());
            pstmt.setString(3, customer.getPhone());

            rs = pstmt.executeQuery();
            if (rs.next()) {
                customer.setCustomerId(rs.getInt("customer_id"));
                customer.setAccountId(rs.getInt("account_id"));
            }
            return customer;
        } catch (SQLException e) {
            throw new DataAccessException("Error inserting customer", e);
        } finally {
            try { if (rs != null) rs.close(); } catch (SQLException ignored) {}
            try { if (pstmt != null) pstmt.close(); } catch (SQLException ignored) {}
            try { if (con != null) con.close(); } catch (SQLException ignored) {}
        }
    }

    public List<Customer> getAllCustomers() throws DataAccessException {
        List<Customer> list = new ArrayList<>();
        String sql = "SELECT * FROM customers";
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            con = ConnectionUtil.getConnection();
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                Customer c = new Customer(
                        rs.getString("name"),
                        rs.getString("email"),
                        rs.getString("phone")
                );
                c.setCustomerId(rs.getInt("customer_id"));
                c.setAccountId(rs.getInt("account_id"));
                list.add(c);
            }
            return list;
        } catch (SQLException e) {
            throw new DataAccessException("Error fetching customers", e);
        } finally {
            try { if (rs != null) rs.close(); } catch (SQLException ignored) {}
            try { if (stmt != null) stmt.close(); } catch (SQLException ignored) {}
            try { if (con != null) con.close(); } catch (SQLException ignored) {}
        }
    }

    public Customer updateCustomer(int id, String newEmail, String newPhone) throws DataAccessException, CustomerNotFoundException {
        String sql = "UPDATE customers SET email=?, phone=? WHERE customer_id=? RETURNING *";
        Connection con = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            con = ConnectionUtil.getConnection();
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, newEmail);
            pstmt.setString(2, newPhone);
            pstmt.setInt(3, id);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                Customer c = new Customer(
                        rs.getString("name"),
                        rs.getString("email"),
                        rs.getString("phone")
                );
                c.setCustomerId(rs.getInt("customer_id"));
                c.setAccountId(rs.getInt("account_id"));
                return c;
            } else {
                throw new CustomerNotFoundException("Customer with ID " + id + " not found.");
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error updating customer", e);
        } finally {
            try { if (rs != null) rs.close(); } catch (SQLException ignored) {}
            try { if (pstmt != null) pstmt.close(); } catch (SQLException ignored) {}
            try { if (con != null) con.close(); } catch (SQLException ignored) {}
        }
    }

    public void deleteCustomer(int id) throws DataAccessException, CustomerNotFoundException {
        String sql = "DELETE FROM customers WHERE customer_id=?";
        Connection con = null;
        PreparedStatement pstmt = null;

        try {
            con = ConnectionUtil.getConnection();
            pstmt = con.prepareStatement(sql);
            pstmt.setInt(1, id);

            int rows = pstmt.executeUpdate();
            if (rows == 0) {
                throw new CustomerNotFoundException("Customer with ID " + id + " not found.");
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error deleting customer", e);
        } finally {
            try { if (pstmt != null) pstmt.close(); } catch (SQLException ignored) {}
            try { if (con != null) con.close(); } catch (SQLException ignored) {}
        }
    }
}

**
package com.bank.service;

import com.bank.entity.Customer;
import com.bank.exception.CustomerNotFoundException;
import com.bank.exception.DataAccessException;

import java.util.List;

public interface CustomerService {
    Customer addCustomer(Customer customer) throws DataAccessException;
    List<Customer> getCustomers() throws DataAccessException;
    Customer updateCustomer(int id, String email, String phone) throws DataAccessException, CustomerNotFoundException;
    void deleteCustomer(int id) throws DataAccessException, CustomerNotFoundException;
}

**
package com.bank.service;

import com.bank.entity.Customer;
import com.bank.exception.CustomerNotFoundException;
import com.bank.exception.DataAccessException;
import com.bank.repository.CustomerRepository;

import java.util.List;

public class CustomerServiceImpl implements CustomerService {
    private final CustomerRepository repo = new CustomerRepository();

    @Override
    public Customer addCustomer(Customer customer) throws DataAccessException {
        return repo.insertCustomer(customer);
    }

    @Override
    public List<Customer> getCustomers() throws DataAccessException {
        return repo.getAllCustomers();
    }

    @Override
    public Customer updateCustomer(int id, String email, String phone) throws DataAccessException, CustomerNotFoundException {
        return repo.updateCustomer(id, email, phone);
    }

    @Override
    public void deleteCustomer(int id) throws DataAccessException, CustomerNotFoundException {
        repo.deleteCustomer(id);
    }
}

**
package com.bank.main;

import com.bank.entity.Customer;
import com.bank.exception.CustomerNotFoundException;
import com.bank.exception.DataAccessException;
import com.bank.exception.InvalidInputException;
import com.bank.service.CustomerService;
import com.bank.service.CustomerServiceImpl;

import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        CustomerService service = new CustomerServiceImpl();

        try {
            while (true) {
                System.out.println("\n===== CUSTOMER MANAGEMENT SYSTEM =====");
                System.out.println("1. Add Customer");
                System.out.println("2. View Customers");
                System.out.println("3. Update Customer");
                System.out.println("4. Delete Customer");
                System.out.println("5. Exit");
                System.out.print("Enter choice: ");

                int choice;
                try {
                    choice = sc.nextInt();
                    sc.nextLine(); 
                } catch (InputMismatchException e) {
                    System.out.println("❌ Invalid input! Please enter a number (1-5).");
                    sc.nextLine();
                    continue;
                }

                try {
                    switch (choice) {
                        case 1:
                            System.out.print("Name: ");
                            String name = sc.nextLine().trim();
                            System.out.print("Email: ");
                            String email = sc.nextLine().trim();
                            System.out.print("Phone: ");
                            String phone = sc.nextLine().trim();

                            validateInput(name, email, phone);

                            Customer newCustomer = new Customer(name, email, phone);
                            Customer added = service.addCustomer(newCustomer);
                            System.out.println("✅ Customer added: " + added);
                            break;

                        case 2:
                            List<Customer> customers = service.getCustomers();
                            if (customers.isEmpty()) {
                                System.out.println("ℹ️ No customers found.");
                            } else {
                                customers.forEach(System.out::println);
                            }
                            break;

                        case 3:
                            System.out.print("Enter Customer ID: ");
                            int id = sc.nextInt();
                            sc.nextLine();
                            System.out.print("Enter new Email: ");
                            String newEmail = sc.nextLine().trim();
                            System.out.print("Enter new Phone: ");
                            String newPhone = sc.nextLine().trim();

                            validateInput("dummy", newEmail, newPhone);

                            Customer updated = service.updateCustomer(id, newEmail, newPhone);
                            System.out.println("✅ Updated customer: " + updated);
                            break;

                        case 4:
                            System.out.print("Enter Customer ID to delete: ");
                            int delId = sc.nextInt();
                            sc.nextLine();
                            service.deleteCustomer(delId);
                            System.out.println("✅ Customer deleted.");
                            break;

                        case 5:
                            System.out.println("👋 Exiting... Goodbye!");
                            return;

                        default:
                            System.out.println("❌ Invalid option! Please enter between 1 and 5.");
                    }
                } catch (InvalidInputException e) {
                    System.out.println("❌ Input Error: " + e.getMessage());
                } catch (CustomerNotFoundException e) {
                    System.out.println("❌ " + e.getMessage());
                } catch (DataAccessException e) {
                    System.out.println("❌ Database error: " + e.getMessage());
                } catch (Exception e) {
                    System.out.println("⚠️ Unexpected error: " + e.getMessage());
                }
            }
        } finally {
            sc.close();
        }
    }

    // Validation logic
    private static void validateInput(String name, String email, String phone) throws InvalidInputException {
        if (name == null || name.isEmpty()) {
            throw new InvalidInputException("Name cannot be empty!");
        }
        if (email == null || !email.contains("@") || !email.contains(".")) {
            throw new InvalidInputException("Invalid email format!");
        }
        if (phone == null || !phone.matches("\\d{10}")) {
            throw new InvalidInputException("Phone must be 10 digits!");
        }
    }
}

CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    account_id SERIAL UNIQUE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(15) NOT NULL
);
